/**
 * Official Xalapa route names provided by the transit authority.
 * Key = route number (1–152), Value = official descriptive name.
 */
export const ROUTE_NAMES: Record<number, string> = {
  1: 'Avila Camacho - Zona UV - Xalapa 2mil - Lomas Verdes - IPE - Bugambilias',
  2: 'Av. Xalapa - Ignacio de la Llave - Zona UV - Rebsamen - Xalapa 2mil - Arco Sur - Lázaro Cárdenas',
  3: 'Av. Xalapa(economía) - 20 noviembre - Lazaro Cardenas | IDA',
  4: 'Lázaro Cardenas - 20 de noviembre - Av.xalapa (economía) | VUELTA',
  5: 'Campo de Tiro - Colonia Hernández Castillo - Sayago',
  6: 'Miradores - Trancas - Tesoreria - Banderilla',
  7: 'Mercado - Pipila - Jardines - Carolino Anaya',
  8: 'Buena Vista - Sauces - Berros - Caxa - Trancas - Pradera - Central Abastos',
  9: 'Reserva Territorial - 20 de Noviembre - Economía - Avenida Xalapa',
  10: 'Escuela Normal Veracruzana - Avenida Xalapa - Economía - Clavijero - Reserva Territorial',
  11: 'Sayago - Calle Nuevo León - Villa Hermosa - Sumidero',
  12: 'Sumidero - Calle Nuevo León - Villa Hermosa - Clavijero',
  13: 'Sayago - Av. Xalapa - Hernández Castillo - Campo de Tiro',
  14: 'Colonia Vicente Guerrero - Campo de Tiro - Col. Revolución - Av. Xalapa - Centro',
  15: 'Chedrahui Caram - Ejidal - Chedrahui Caram',
  16: 'Mártires 28 de Agosto - USISVER - Miguel Alemán',
  17: 'Mártires 28 de Agosto - Lazaro Cardenas',
  18: 'Ruta Macuiltepetl - Miguel Alemán - Cerro de Macuiltepetl - Centro',
  19: 'Calvario - Panteón - Técnica 72',
  20: 'Murillo Vidal - Plaza Américas - Torre Ánimas - Sev - Coapexpan - Terminal',
  21: 'El Olmo - Torre Animas - Murillo Vidal - Coapexpan',
  22: 'El Haya - Zona UV - Bugambilias',
  23: 'Bugambilias - Zona UV - El Haya',
  24: 'El Haya - Centro - Ojo de Agua',
  25: 'Ojo de Agua - Zona UV - El Haya',
  26: 'Col. Veracruz - 20 de Noviembre - Central de Abastos',
  27: 'Central de Abastos - 20 de Noviembre - Col. Veracruz',
  28: 'Artículo 3ro - Avila Camacho',
  29: 'Haciendas - Centro - Art 3ro',
  30: 'San Andrés Tlalnehuayocan - Luz del Barrio - Central de Abastos',
  31: 'Marina Nacional - Pipila - Santa Rosa',
  32: 'San Andrés Tlalnehuayocan - Luz del Barrio - Central de Abastos',
  33: 'San Andrés Tlalnehuayocan - Luz del Barrio - Clavijero - Zipor',
  34: 'Las Fuentes - Mercado - San Andrés Tlalnehuayocan',
  35: 'La Haciendita - Caxa - Central de Abastos',
  36: 'Central de Abastos - Caxa - La Haciendita',
  37: 'Experimental - Plaza Cristal - Central de Abastos',
  38: 'Central de Abastos - Plaza Cristal - Experimental',
  39: 'La Haciendita - Caxa - Central de Abastos',
  40: 'Central de Abastos - Caxa - La Haciendita',
  41: 'Experimental - Cristal - Central de Abastos',
  42: 'Central de Abastos - Plaza Cristal - Experimental',
  43: 'Homex - Vasconcelos - Av. Xalapa - Centro',
  44: 'Centro - Av. Xalapa - Vasconcelos - Homex',
  45: 'Col México - Lucas Martín - Av. Xalapa - Centro',
  46: 'Centro - Av. Xalapa - Lucas Martín - Col. México',
  47: 'Campo de Tiro - Revolución - Clavijero',
  48: 'Clavijero - Revolución - Campo de Tiro',
  49: 'El Moral - Revolución - Clavijero',
  50: 'Clavijero - Revolución - El Moral',
  51: 'Col Higueras - Lázaro Cárdenas - Centro - Zona UV',
  52: 'Zona UV - Centro - Lázaro Cárdenas - Higueras',
  53: 'Sefiplan - Lazaro Cardenas - Cto. Presidentes - Ruiz Cortinez',
  54: 'Reforma - Mercado - Sumidero',
  55: 'Sumidero - Mercado - Reforma',
  56: 'Campo de Tiro - Av. Xalapa - Av. México - Clavijero',
  57: 'Clavijero - Av. Xalapa - Av. México - Campo de Tiro',
  58: 'Bugambilias - Lázaro Cárdenas - Avila Camacho - Sauces',
  59: 'Bugambilias - Ávila Camacho - Av. Xalapa',
  60: 'Col. Revolución - Av. Xalapa - Sayago',
  61: 'Col. Revolución - Av. Xalapa - Sayago',
  62: 'Col. Higueras - Av. Américas - Av. Xalapa',
  63: 'Av. Xalapa - Av. Américas - Col. Higueras',
  64: 'San Andrés - Av. Lázaro Cárdenas - Trancas',
  65: 'Trancas - Av. Lázaro Cárdenas - San Andrés',
  66: 'Col. Marina Nacional - Av. 20 de Noviembre - Poeta Jesús Díaz',
  67: 'Poeta Jesús Díaz - Av. 20 de Noviembre - Col. Marina Nacional',
  68: 'Trancas - 20 de Noviembre - Arteaga',
  69: 'Arteaga - 20 de Noviembre - Trancas',
  70: 'Trancas - Lázaro Cardenas - 20 de Noviembre - Plaza Crystal - Jardines - Sumidero - Campo de Tiro | IDA',
  71: 'Trancas - Lázaro Cardenas - 20 de Noviembre - Plaza Crystal - Jardines - Sumidero - Campo de Tiro | VUELTA',
  72: 'Santiago Andres - M. 28 de Agosto - Mercado',
  73: 'Mercado - M. 28 de Agosto - Santiago Andres',
  74: 'Lomas Verdes - Xalapa 2000 - Rebsamen - Zona UV - Centro',
  75: 'Centro - Berros - Rebsamen - Xalapa 2000 - Lomas Verdes - Arco Sur - Tecnológico',
  76: 'Av. Americas - Pipila - Lazaro Cárdenas - Murillo Vidal - Berros - Rebsamen - Tecnológico',
  77: 'Plaza Cristal - Lázaro Cárdenas - Chilpancingo - Comercial - Ruiz Cortinez - Luz del Barrio',
  78: 'Luz del Barrio - Casa Blanca',
  79: 'Coatepec Porthos - Xalapa Rotonda',
  80: 'Xalapa - Encinos | Carro Sauces',
  81: 'Mercado - Centro - Cristal - Peñascal - Sumidero - Campo de Tiro',
  82: 'Articulo 3ro - Lázaro Cárdenas - Trancas - La Pradera - Las Haciendas',
  83: 'Central de Abastos - La Martinica (Banderilla)',
  84: 'Las Trancas - FOVISSSTE',
  85: '20 de Noviembre - Pacho Nuevo',
  86: 'Central de Abastos - Campo de Tiro',
  87: 'Centro - Clavijero - Casa Blanca',
  88: 'Casa Blanca - Plaza Cristal',
  89: 'Poeta Jesus Dias - Sumidero',
  90: 'Casa Blanca - Pipila - Clavijero',
  91: 'Pipila - Sumidero',
  92: 'Terminal - Mercado - Sumidero',
  93: 'Sumidero - Jardines',
  94: 'Sumidero - Centro - Plaza Cristal - Calvario',
  95: 'Mercado - 28 de agosto - San Antonio',
  96: 'San Antonio - 28 de agosto - Mercado',
  97: 'Xocotla 27 de agosto - Mercado',
  98: 'Ávila Camacho - Ignacio de la Llave - Sauces - Zona UV',
  99: 'Higueras - Casa Blanca - Lázaro Cárdenas - 20 de Noviembre - Zona UV - Venustiano Carranza',
  100: 'Carranza - Sauces - Ruiz Cortinez - Av. Xalapa - Poeta - 20 de Noviembre - Lázaro Cárdenas',
  101: 'Coapexpan - Araucarias - Torre Animas',
  102: 'Coapexpan - Inst. Tec. 72',
  103: 'Tec 72 - Coapexpan',
  104: 'Instituto Tecnológico - Arco Sur - Rebsamen - Sauces - Avila Camacho - Americas - Pipila - Lázaro Cárdenas - Arco Sur - Instituto Tecnológico',
  105: 'Estación - Zona UV',
  106: 'Jardines - Estación - Centro',
  107: 'Centro - Central de Abastos',
  108: 'Buena Vista - Centro',
  109: 'Coapexpan - M. Vidal - Torre Animas - Araucarias',
  110: 'FOVISSSTE - Calvario - IMSS',
  111: 'FOVISSSTE - Calvario',
  112: 'Ruiz Cortines - FOVISSTE - Lazaro Cardenas',
  113: 'Ruiz Cortines - Zona UV',
  114: 'Lomas Verdes - Medicina',
  115: 'Estación - Villa Hermosa - Ruiz Cortinez - Sauces',
  116: 'Escuela Normal - Juarez - Centro - Berros - Rebsamen - Ojo de Agua',
  117: 'Bugambilias - Trancas - Lázaro Cárdenas - SEFIPLAN - Av. Xalapa - Ignacio de la Llave - IMSS - Carranza - Zona UV - Rebsamen - Xalapa 2000 - Arco Sur - Tecnologico - Bugambilias',
  118: 'Articulo 3ro - Ruiz Cortinez - SEFIPLAN - Lázaro Cárdenas - Chedraui Caram - Plaza Americas - Trancas - Arco Sur - Tecnologico',
  119: 'Torres - Centro',
  120: 'Xocotla - Martires 28 de Agosto - Sayago',
  121: 'Buena Vista - Central de Abastos',
  122: 'Pastoresa - Murillo Vidal - Centro',
  123: 'Sauces - Ojo de Agua',
  124: 'Campo de Tiro - Crystal - Mercado',
  125: 'Estación - Calvario',
  126: 'Arco Sur - Rebsamen - Tecnológico - Trancas - Lázaro Cárdenas - Pipila - Américas - Avila Camacho - Ignacio de la Llave - Sauces - Zona UV - Rebsamen - Arco Sur',
  127: 'Lomas Verdes - Medicina',
  128: 'Estación - Terminal Bolivia',
  129: 'Estación - Ignacio de la Llave',
  130: 'Calvario - Terminal',
  131: 'Articulo 3ro - Zona UV - Berros - 20 de Noviembre - Av. Xalapa - Avila Camacho - Ruiz Cortinez',
  132: 'Lazaro Cardenas - Ruiz Cortinez',
  133: 'SEFIPLAN - Lazaro Cardenas',
  134: 'SEFIPLAN - Avila Camacho',
  135: 'Tecnica 72 - Circunvalacion',
  136: 'Coapexpan - Tecnica 72',
  137: 'Tecnica 72 - Aguascalientes',
  138: 'Fovissste - Lerdo de Tejada',
  139: 'Fovissste - IMSS',
  140: 'Fovissste - San Bruno - Trancas',
  141: 'Pastoresa - Mercado',
  142: 'Luz del Barrio - Plaza Crystal',
  143: 'Rancho Viejo - Xalapa',
  144: 'Mercado - Sumidero',
  145: 'Carolino Anaya - IMSS',
  146: 'Santa Rosa - Estación',
  147: 'Martires de Chicago - Mercado',
  148: 'Coapexpan - SEC',
  149: 'Coapexpan - Araucarias',
  150: 'Coapexpan - Araucarias',
  151: 'Higueras - Mercado',
  152: 'Circuito Presidentes - Rebsamen - Xalapa 2000 - Arco Sur - Trancas - Lazaro Cardenas - Ruiz Cortinez - Sauces - Velódromo',
};

/** Extract "first stop → last stop" from an official route name */
export function parseEndpoints(name: string): [string, string] | null {
  const clean = name.replace(/\s*\|.*$/, '').trim();
  const parts = clean.split(' - ').map(s => s.trim()).filter(Boolean);
  if (parts.length < 2) return null;
  return [parts[0], parts[parts.length - 1]];
}
